// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type AssociationModifyRequest struct {
	Association string `pathParam:"style=simple,explode=false,name=association"`
	// An association object
	AssociationModify components.AssociationModify `request:"mediaType=application/json"`
}

func (o *AssociationModifyRequest) GetAssociation() string {
	if o == nil {
		return ""
	}
	return o.Association
}

func (o *AssociationModifyRequest) GetAssociationModify() components.AssociationModify {
	if o == nil {
		return components.AssociationModify{}
	}
	return o.AssociationModify
}

type AssociationModifyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// swap successful
	RegularResponse *components.RegularResponse
	Headers         map[string][]string
}

func (o *AssociationModifyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AssociationModifyResponse) GetRegularResponse() *components.RegularResponse {
	if o == nil {
		return nil
	}
	return o.RegularResponse
}

func (o *AssociationModifyResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
