// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type AttachmentsListRequest struct {
	Volume   string `pathParam:"style=simple,explode=false,name=volume"`
	Snapshot string `pathParam:"style=simple,explode=false,name=snapshot"`
}

func (o *AttachmentsListRequest) GetVolume() string {
	if o == nil {
		return ""
	}
	return o.Volume
}

func (o *AttachmentsListRequest) GetSnapshot() string {
	if o == nil {
		return ""
	}
	return o.Snapshot
}

type AttachmentsListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of attachments
	Attachments []components.Attachment
	Headers     map[string][]string
}

func (o *AttachmentsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AttachmentsListResponse) GetAttachments() []components.Attachment {
	if o == nil {
		return nil
	}
	return o.Attachments
}

func (o *AttachmentsListResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
