// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type AttachmentsListForVolumeRequest struct {
	Volume string `pathParam:"style=simple,explode=false,name=volume"`
}

func (o *AttachmentsListForVolumeRequest) GetVolume() string {
	if o == nil {
		return ""
	}
	return o.Volume
}

type AttachmentsListForVolumeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of attachments
	Attachments []components.Attachment
	Headers     map[string][]string
}

func (o *AttachmentsListForVolumeResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AttachmentsListForVolumeResponse) GetAttachments() []components.Attachment {
	if o == nil {
		return nil
	}
	return o.Attachments
}

func (o *AttachmentsListForVolumeResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
