// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type AttachmentCreateRequest struct {
	Volume   string `pathParam:"style=simple,explode=false,name=volume"`
	Snapshot string `pathParam:"style=simple,explode=false,name=snapshot"`
	// An Attachment object
	Attachment components.AttachmentInput `request:"mediaType=application/json"`
}

func (o *AttachmentCreateRequest) GetVolume() string {
	if o == nil {
		return ""
	}
	return o.Volume
}

func (o *AttachmentCreateRequest) GetSnapshot() string {
	if o == nil {
		return ""
	}
	return o.Snapshot
}

func (o *AttachmentCreateRequest) GetAttachment() components.AttachmentInput {
	if o == nil {
		return components.AttachmentInput{}
	}
	return o.Attachment
}

type AttachmentCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// New attachment was created successfully
	RegularResponse *components.RegularResponse
	Headers         map[string][]string
}

func (o *AttachmentCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AttachmentCreateResponse) GetRegularResponse() *components.RegularResponse {
	if o == nil {
		return nil
	}
	return o.RegularResponse
}

func (o *AttachmentCreateResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
