// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type AttachmentsListAllResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of all attachments
	Attachments []components.Attachment
	Headers     map[string][]string
}

func (o *AttachmentsListAllResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AttachmentsListAllResponse) GetAttachments() []components.Attachment {
	if o == nil {
		return nil
	}
	return o.Attachments
}

func (o *AttachmentsListAllResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
