// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type AttachmentModifyRequest struct {
	Volume   string `pathParam:"style=simple,explode=false,name=volume"`
	Snapshot string `pathParam:"style=simple,explode=false,name=snapshot"`
	Node     string `pathParam:"style=simple,explode=false,name=node"`
	// An Attachment object
	Attachment components.AttachmentInput `request:"mediaType=application/json"`
}

func (o *AttachmentModifyRequest) GetVolume() string {
	if o == nil {
		return ""
	}
	return o.Volume
}

func (o *AttachmentModifyRequest) GetSnapshot() string {
	if o == nil {
		return ""
	}
	return o.Snapshot
}

func (o *AttachmentModifyRequest) GetNode() string {
	if o == nil {
		return ""
	}
	return o.Node
}

func (o *AttachmentModifyRequest) GetAttachment() components.AttachmentInput {
	if o == nil {
		return components.AttachmentInput{}
	}
	return o.Attachment
}

type AttachmentModifyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// An attachment was updated successfully
	RegularResponse *components.RegularResponse
	Headers         map[string][]string
}

func (o *AttachmentModifyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AttachmentModifyResponse) GetRegularResponse() *components.RegularResponse {
	if o == nil {
		return nil
	}
	return o.RegularResponse
}

func (o *AttachmentModifyResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
