// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type AttachmentGetRequest struct {
	Volume   string `pathParam:"style=simple,explode=false,name=volume"`
	Snapshot string `pathParam:"style=simple,explode=false,name=snapshot"`
	Node     string `pathParam:"style=simple,explode=false,name=node"`
}

func (o *AttachmentGetRequest) GetVolume() string {
	if o == nil {
		return ""
	}
	return o.Volume
}

func (o *AttachmentGetRequest) GetSnapshot() string {
	if o == nil {
		return ""
	}
	return o.Snapshot
}

func (o *AttachmentGetRequest) GetNode() string {
	if o == nil {
		return ""
	}
	return o.Node
}

type AttachmentGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Properties of an attachment
	Attachment *components.Attachment
	Headers    map[string][]string
}

func (o *AttachmentGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AttachmentGetResponse) GetAttachment() *components.Attachment {
	if o == nil {
		return nil
	}
	return o.Attachment
}

func (o *AttachmentGetResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
