// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type ConnectivitiesListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of connectivities
	Connectivities []components.Connectivity
	Headers        map[string][]string
}

func (o *ConnectivitiesListResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ConnectivitiesListResponse) GetConnectivities() []components.Connectivity {
	if o == nil {
		return nil
	}
	return o.Connectivities
}

func (o *ConnectivitiesListResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
