// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type ConnectivityGetRequest struct {
	Connectivity string `pathParam:"style=simple,explode=false,name=connectivity"`
}

func (o *ConnectivityGetRequest) GetConnectivity() string {
	if o == nil {
		return ""
	}
	return o.Connectivity
}

type ConnectivityGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Properties of a connectivity
	Connectivity *components.Connectivity
	Headers      map[string][]string
}

func (o *ConnectivityGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ConnectivityGetResponse) GetConnectivity() *components.Connectivity {
	if o == nil {
		return nil
	}
	return o.Connectivity
}

func (o *ConnectivityGetResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
