// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type JobDeleteRequest struct {
	Job int64 `pathParam:"style=simple,explode=false,name=job"`
}

func (o *JobDeleteRequest) GetJob() int64 {
	if o == nil {
		return 0
	}
	return o.Job
}

type JobDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A job was deleted successfully
	RegularResponse *components.RegularResponse
	Headers         map[string][]string
}

func (o *JobDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *JobDeleteResponse) GetRegularResponse() *components.RegularResponse {
	if o == nil {
		return nil
	}
	return o.RegularResponse
}

func (o *JobDeleteResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
