// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type JobResumeSuspendRequest struct {
	Job   int64 `pathParam:"style=simple,explode=false,name=job"`
	State int64 `pathParam:"style=simple,explode=false,name=state"`
}

func (o *JobResumeSuspendRequest) GetJob() int64 {
	if o == nil {
		return 0
	}
	return o.Job
}

func (o *JobResumeSuspendRequest) GetState() int64 {
	if o == nil {
		return 0
	}
	return o.State
}

type JobResumeSuspendResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Operation completed successfully
	RegularResponse *components.RegularResponse
	Headers         map[string][]string
}

func (o *JobResumeSuspendResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *JobResumeSuspendResponse) GetRegularResponse() *components.RegularResponse {
	if o == nil {
		return nil
	}
	return o.RegularResponse
}

func (o *JobResumeSuspendResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
