// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type JobsListRequest struct {
	Internal *bool  `queryParam:"style=form,explode=true,name=internal"`
	Page     *int64 `queryParam:"style=form,explode=true,name=page"`
	Count    *int64 `queryParam:"style=form,explode=true,name=count"`
}

func (o *JobsListRequest) GetInternal() *bool {
	if o == nil {
		return nil
	}
	return o.Internal
}

func (o *JobsListRequest) GetPage() *int64 {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *JobsListRequest) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

type JobsListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of jobs
	Jobs    []components.Job
	Headers map[string][]string
}

func (o *JobsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *JobsListResponse) GetJobs() []components.Job {
	if o == nil {
		return nil
	}
	return o.Jobs
}

func (o *JobsListResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
