// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type MediaDiagnoseRequest struct {
	Media string `pathParam:"style=simple,explode=false,name=media"`
	// Tenant ID
	Tenant string `pathParam:"style=simple,explode=false,name=tenant"`
}

func (o *MediaDiagnoseRequest) GetMedia() string {
	if o == nil {
		return ""
	}
	return o.Media
}

func (o *MediaDiagnoseRequest) GetTenant() string {
	if o == nil {
		return ""
	}
	return o.Tenant
}

type MediaDiagnoseResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Operation completed successfully
	RegularResponse *components.RegularResponse
	Headers         map[string][]string
}

func (o *MediaDiagnoseResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *MediaDiagnoseResponse) GetRegularResponse() *components.RegularResponse {
	if o == nil {
		return nil
	}
	return o.RegularResponse
}

func (o *MediaDiagnoseResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
