// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type MediaProfileModifyRequest struct {
	Media string `pathParam:"style=simple,explode=false,name=media"`
	// A Media Profile object
	MediaProfile components.MediaProfile `request:"mediaType=application/json"`
}

func (o *MediaProfileModifyRequest) GetMedia() string {
	if o == nil {
		return ""
	}
	return o.Media
}

func (o *MediaProfileModifyRequest) GetMediaProfile() components.MediaProfile {
	if o == nil {
		return components.MediaProfile{}
	}
	return o.MediaProfile
}

type MediaProfileModifyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A media profile was updated successfully
	RegularResponse *components.RegularResponse
	Headers         map[string][]string
}

func (o *MediaProfileModifyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *MediaProfileModifyResponse) GetRegularResponse() *components.RegularResponse {
	if o == nil {
		return nil
	}
	return o.RegularResponse
}

func (o *MediaProfileModifyResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
