// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type MediaListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of media
	Media   []components.Media
	Headers map[string][]string
}

func (o *MediaListResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *MediaListResponse) GetMedia() []components.Media {
	if o == nil {
		return nil
	}
	return o.Media
}

func (o *MediaListResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
