// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type NetworkGetRequest struct {
	Network string `pathParam:"style=simple,explode=false,name=network"`
}

func (o *NetworkGetRequest) GetNetwork() string {
	if o == nil {
		return ""
	}
	return o.Network
}

type NetworkGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Properties of a network
	Network *components.Network
	Headers map[string][]string
}

func (o *NetworkGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *NetworkGetResponse) GetNetwork() *components.Network {
	if o == nil {
		return nil
	}
	return o.Network
}

func (o *NetworkGetResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
