// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type NetworksListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of networks
	Networks []components.Network
	Headers  map[string][]string
}

func (o *NetworksListResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *NetworksListResponse) GetNetworks() []components.Network {
	if o == nil {
		return nil
	}
	return o.Networks
}

func (o *NetworksListResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
