// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type NetworkModifyRequest struct {
	NetworkPathParameter string `pathParam:"style=simple,explode=false,name=network"`
	// A Network object
	Network1 components.Network `request:"mediaType=application/json"`
}

func (o *NetworkModifyRequest) GetNetworkPathParameter() string {
	if o == nil {
		return ""
	}
	return o.NetworkPathParameter
}

func (o *NetworkModifyRequest) GetNetwork1() components.Network {
	if o == nil {
		return components.Network{}
	}
	return o.Network1
}

type NetworkModifyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A network was updated successfully
	RegularResponse *components.RegularResponse
	Headers         map[string][]string
}

func (o *NetworkModifyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *NetworkModifyResponse) GetRegularResponse() *components.RegularResponse {
	if o == nil {
		return nil
	}
	return o.RegularResponse
}

func (o *NetworkModifyResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
