// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type NetworkDeleteRequest struct {
	Network string `pathParam:"style=simple,explode=false,name=network"`
}

func (o *NetworkDeleteRequest) GetNetwork() string {
	if o == nil {
		return ""
	}
	return o.Network
}

type NetworkDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A network was deleted successfully
	RegularResponse *components.RegularResponse
	Headers         map[string][]string
}

func (o *NetworkDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *NetworkDeleteResponse) GetRegularResponse() *components.RegularResponse {
	if o == nil {
		return nil
	}
	return o.RegularResponse
}

func (o *NetworkDeleteResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
