// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type NodeSetTagsRequest struct {
	// Name of node to return
	Node string `pathParam:"style=simple,explode=false,name=node"`
	// user defined tags
	RequestBody map[string]string `request:"mediaType=application/json"`
}

func (o *NodeSetTagsRequest) GetNode() string {
	if o == nil {
		return ""
	}
	return o.Node
}

func (o *NodeSetTagsRequest) GetRequestBody() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.RequestBody
}

type NodeSetTagsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A node set tags was successful
	RegularResponse *components.RegularResponse
	Headers         map[string][]string
}

func (o *NodeSetTagsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *NodeSetTagsResponse) GetRegularResponse() *components.RegularResponse {
	if o == nil {
		return nil
	}
	return o.RegularResponse
}

func (o *NodeSetTagsResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
