// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type NodeUpgradeForSupportRequest struct {
	// Name of tenant to upgrade
	Tenant string `pathParam:"style=simple,explode=false,name=tenant"`
	// Name of node to upgrade
	Node string `pathParam:"style=simple,explode=false,name=node"`
	// Connector Version
	NodeVersion *components.NodeVersion `request:"mediaType=application/json"`
}

func (o *NodeUpgradeForSupportRequest) GetTenant() string {
	if o == nil {
		return ""
	}
	return o.Tenant
}

func (o *NodeUpgradeForSupportRequest) GetNode() string {
	if o == nil {
		return ""
	}
	return o.Node
}

func (o *NodeUpgradeForSupportRequest) GetNodeVersion() *components.NodeVersion {
	if o == nil {
		return nil
	}
	return o.NodeVersion
}

type NodeUpgradeForSupportResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Node upgrade started successfully
	RegularResponse *components.RegularResponse
	Headers         map[string][]string
}

func (o *NodeUpgradeForSupportResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *NodeUpgradeForSupportResponse) GetRegularResponse() *components.RegularResponse {
	if o == nil {
		return nil
	}
	return o.RegularResponse
}

func (o *NodeUpgradeForSupportResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
