// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type NodeDescribeRequest struct {
	Node string `pathParam:"style=simple,explode=false,name=node"`
}

func (o *NodeDescribeRequest) GetNode() string {
	if o == nil {
		return ""
	}
	return o.Node
}

type NodeDescribeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Description of a node
	NodeDescribeResponse *components.NodeDescribeResponse
	Headers              map[string][]string
}

func (o *NodeDescribeResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *NodeDescribeResponse) GetNodeDescribeResponse() *components.NodeDescribeResponse {
	if o == nil {
		return nil
	}
	return o.NodeDescribeResponse
}

func (o *NodeDescribeResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
