// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type NodeCollectLogsRequest struct {
	// Name of node
	Node string `pathParam:"style=simple,explode=false,name=node"`
	// Tenant ID
	Tenant string `pathParam:"style=simple,explode=false,name=tenant"`
}

func (o *NodeCollectLogsRequest) GetNode() string {
	if o == nil {
		return ""
	}
	return o.Node
}

func (o *NodeCollectLogsRequest) GetTenant() string {
	if o == nil {
		return ""
	}
	return o.Tenant
}

type NodeCollectLogsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Node collect logs job  was created successfully
	RegularResponse *components.RegularResponse
	Headers         map[string][]string
}

func (o *NodeCollectLogsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *NodeCollectLogsResponse) GetRegularResponse() *components.RegularResponse {
	if o == nil {
		return nil
	}
	return o.RegularResponse
}

func (o *NodeCollectLogsResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
