// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/internal/utils"
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type NodeDeleteRequest struct {
	// Name of node to return
	Node  string `pathParam:"style=simple,explode=false,name=node"`
	Force *bool  `default:"false" queryParam:"style=form,explode=true,name=force"`
}

func (n NodeDeleteRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NodeDeleteRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *NodeDeleteRequest) GetNode() string {
	if o == nil {
		return ""
	}
	return o.Node
}

func (o *NodeDeleteRequest) GetForce() *bool {
	if o == nil {
		return nil
	}
	return o.Force
}

type NodeDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A node delete job was created successfully
	RegularResponse *components.RegularResponse
	Headers         map[string][]string
}

func (o *NodeDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *NodeDeleteResponse) GetRegularResponse() *components.RegularResponse {
	if o == nil {
		return nil
	}
	return o.RegularResponse
}

func (o *NodeDeleteResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
