// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type NodeRepairRequest struct {
	// Name of node
	Node string `pathParam:"style=simple,explode=false,name=node"`
	// Tenant ID
	Tenant string `pathParam:"style=simple,explode=false,name=tenant"`
	// A repair node object
	RepairCmds components.RepairCmds `request:"mediaType=application/json"`
}

func (o *NodeRepairRequest) GetNode() string {
	if o == nil {
		return ""
	}
	return o.Node
}

func (o *NodeRepairRequest) GetTenant() string {
	if o == nil {
		return ""
	}
	return o.Tenant
}

func (o *NodeRepairRequest) GetRepairCmds() components.RepairCmds {
	if o == nil {
		return components.RepairCmds{}
	}
	return o.RepairCmds
}

type NodeRepairResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Node Repair job was created successfully
	RegularResponse *components.RegularResponse
	Headers         map[string][]string
}

func (o *NodeRepairResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *NodeRepairResponse) GetRegularResponse() *components.RegularResponse {
	if o == nil {
		return nil
	}
	return o.RegularResponse
}

func (o *NodeRepairResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
