// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type OptionsNodesUpgradeNodeRequest struct {
	// Name of node to upgrade
	Node string `pathParam:"style=simple,explode=false,name=node"`
}

func (o *OptionsNodesUpgradeNodeRequest) GetNode() string {
	if o == nil {
		return ""
	}
	return o.Node
}

type OptionsNodesUpgradeNodeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// 500 response
	ErrorResponse *components.ErrorResponse
	Headers       map[string][]string
}

func (o *OptionsNodesUpgradeNodeResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OptionsNodesUpgradeNodeResponse) GetErrorResponse() *components.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}

func (o *OptionsNodesUpgradeNodeResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
