// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/VolumezTech/volumez-sdk/models/components"
)

type OptionsChartsProxyRequest struct {
	Proxy string `pathParam:"style=simple,explode=false,name=proxy"`
}

func (o *OptionsChartsProxyRequest) GetProxy() string {
	if o == nil {
		return ""
	}
	return o.Proxy
}

type OptionsChartsProxyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Headers  map[string][]string
}

func (o *OptionsChartsProxyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OptionsChartsProxyResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
