// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type OptionsNodesUpgradeNodeTenantTenantRequest struct {
	// Name of tenant to upgrade
	Tenant string `pathParam:"style=simple,explode=false,name=tenant"`
	// Name of node to upgrade
	Node string `pathParam:"style=simple,explode=false,name=node"`
}

func (o *OptionsNodesUpgradeNodeTenantTenantRequest) GetTenant() string {
	if o == nil {
		return ""
	}
	return o.Tenant
}

func (o *OptionsNodesUpgradeNodeTenantTenantRequest) GetNode() string {
	if o == nil {
		return ""
	}
	return o.Node
}

type OptionsNodesUpgradeNodeTenantTenantResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// 500 response
	ErrorResponse *components.ErrorResponse
	Headers       map[string][]string
}

func (o *OptionsNodesUpgradeNodeTenantTenantResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OptionsNodesUpgradeNodeTenantTenantResponse) GetErrorResponse() *components.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}

func (o *OptionsNodesUpgradeNodeTenantTenantResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
