// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/internal/utils"
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type OptionsExportsExportRequest struct {
	Export string `pathParam:"style=simple,explode=false,name=export"`
	Force  *bool  `default:"false" queryParam:"style=form,explode=true,name=force"`
}

func (o OptionsExportsExportRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OptionsExportsExportRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *OptionsExportsExportRequest) GetExport() string {
	if o == nil {
		return ""
	}
	return o.Export
}

func (o *OptionsExportsExportRequest) GetForce() *bool {
	if o == nil {
		return nil
	}
	return o.Force
}

type OptionsExportsExportResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// 500 response
	ErrorResponse *components.ErrorResponse
	Headers       map[string][]string
}

func (o *OptionsExportsExportResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OptionsExportsExportResponse) GetErrorResponse() *components.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}

func (o *OptionsExportsExportResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
