// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type OptionsJobsJobResumeSuspendStateRequest struct {
	Job   int64 `pathParam:"style=simple,explode=false,name=job"`
	State int64 `pathParam:"style=simple,explode=false,name=state"`
}

func (o *OptionsJobsJobResumeSuspendStateRequest) GetJob() int64 {
	if o == nil {
		return 0
	}
	return o.Job
}

func (o *OptionsJobsJobResumeSuspendStateRequest) GetState() int64 {
	if o == nil {
		return 0
	}
	return o.State
}

type OptionsJobsJobResumeSuspendStateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// 500 response
	ErrorResponse *components.ErrorResponse
	Headers       map[string][]string
}

func (o *OptionsJobsJobResumeSuspendStateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OptionsJobsJobResumeSuspendStateResponse) GetErrorResponse() *components.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}

func (o *OptionsJobsJobResumeSuspendStateResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
