// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type OptionsLogTenantidLogfileRequest struct {
	Logfile  string `pathParam:"style=simple,explode=false,name=logfile"`
	Tenantid string `pathParam:"style=simple,explode=false,name=tenantid"`
}

func (o *OptionsLogTenantidLogfileRequest) GetLogfile() string {
	if o == nil {
		return ""
	}
	return o.Logfile
}

func (o *OptionsLogTenantidLogfileRequest) GetTenantid() string {
	if o == nil {
		return ""
	}
	return o.Tenantid
}

type OptionsLogTenantidLogfileResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Headers  map[string][]string
}

func (o *OptionsLogTenantidLogfileResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OptionsLogTenantidLogfileResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
