// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type OptionsPoliciesPolicySizeSizeZoneZoneRequest struct {
	Policy string `pathParam:"style=simple,explode=false,name=policy"`
	Size   int64  `pathParam:"style=simple,explode=false,name=size"`
	Zone   string `pathParam:"style=simple,explode=false,name=zone"`
}

func (o *OptionsPoliciesPolicySizeSizeZoneZoneRequest) GetPolicy() string {
	if o == nil {
		return ""
	}
	return o.Policy
}

func (o *OptionsPoliciesPolicySizeSizeZoneZoneRequest) GetSize() int64 {
	if o == nil {
		return 0
	}
	return o.Size
}

func (o *OptionsPoliciesPolicySizeSizeZoneZoneRequest) GetZone() string {
	if o == nil {
		return ""
	}
	return o.Zone
}

type OptionsPoliciesPolicySizeSizeZoneZoneResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// 500 response
	ErrorResponse *components.ErrorResponse
	Headers       map[string][]string
}

func (o *OptionsPoliciesPolicySizeSizeZoneZoneResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OptionsPoliciesPolicySizeSizeZoneZoneResponse) GetErrorResponse() *components.ErrorResponse {
	if o == nil {
		return nil
	}
	return o.ErrorResponse
}

func (o *OptionsPoliciesPolicySizeSizeZoneZoneResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
