// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type PolicyGetRequest struct {
	Policy string `pathParam:"style=simple,explode=false,name=policy"`
}

func (o *PolicyGetRequest) GetPolicy() string {
	if o == nil {
		return ""
	}
	return o.Policy
}

type PolicyGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Properties of a policy
	Policy  *components.Policy
	Headers map[string][]string
}

func (o *PolicyGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PolicyGetResponse) GetPolicy() *components.Policy {
	if o == nil {
		return nil
	}
	return o.Policy
}

func (o *PolicyGetResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
