// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type PoliciesListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of policies
	Policies []components.Policy
	Headers  map[string][]string
}

func (o *PoliciesListResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PoliciesListResponse) GetPolicies() []components.Policy {
	if o == nil {
		return nil
	}
	return o.Policies
}

func (o *PoliciesListResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
