// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type PolicyModifyRequest struct {
	PolicyPathParameter string `pathParam:"style=simple,explode=false,name=policy"`
	// A Policy object
	Policy1 components.PolicyInput `request:"mediaType=application/json"`
}

func (o *PolicyModifyRequest) GetPolicyPathParameter() string {
	if o == nil {
		return ""
	}
	return o.PolicyPathParameter
}

func (o *PolicyModifyRequest) GetPolicy1() components.PolicyInput {
	if o == nil {
		return components.PolicyInput{}
	}
	return o.Policy1
}

type PolicyModifyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A policy was updated successfully
	RegularResponse *components.RegularResponse
	Headers         map[string][]string
}

func (o *PolicyModifyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PolicyModifyResponse) GetRegularResponse() *components.RegularResponse {
	if o == nil {
		return nil
	}
	return o.RegularResponse
}

func (o *PolicyModifyResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
