// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type PolicyPlanRequest struct {
	Policy        string  `pathParam:"style=simple,explode=false,name=policy"`
	Size          int64   `pathParam:"style=simple,explode=false,name=size"`
	Zone          string  `pathParam:"style=simple,explode=false,name=zone"`
	CapacityGroup *string `queryParam:"style=form,explode=true,name=capacity_group"`
}

func (o *PolicyPlanRequest) GetPolicy() string {
	if o == nil {
		return ""
	}
	return o.Policy
}

func (o *PolicyPlanRequest) GetSize() int64 {
	if o == nil {
		return 0
	}
	return o.Size
}

func (o *PolicyPlanRequest) GetZone() string {
	if o == nil {
		return ""
	}
	return o.Zone
}

func (o *PolicyPlanRequest) GetCapacityGroup() *string {
	if o == nil {
		return nil
	}
	return o.CapacityGroup
}

type PolicyPlanResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Policy volume group plan
	Plan    *components.Plan
	Headers map[string][]string
}

func (o *PolicyPlanResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PolicyPlanResponse) GetPlan() *components.Plan {
	if o == nil {
		return nil
	}
	return o.Plan
}

func (o *PolicyPlanResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
