// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type RequestChangePasswordResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Request for password change done successfully
	RegularResponse *components.RegularResponse
	Headers         map[string][]string
}

func (o *RequestChangePasswordResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RequestChangePasswordResponse) GetRegularResponse() *components.RegularResponse {
	if o == nil {
		return nil
	}
	return o.RegularResponse
}

func (o *RequestChangePasswordResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
