// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type SignInResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Sign in was successful
	SignInResponse *components.SignInResponse
	Headers        map[string][]string
}

func (o *SignInResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SignInResponse) GetSignInResponse() *components.SignInResponse {
	if o == nil {
		return nil
	}
	return o.SignInResponse
}

func (o *SignInResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
