// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type SnapshotModifyRequest struct {
	Volume                string `pathParam:"style=simple,explode=false,name=volume"`
	SnapshotPathParameter string `pathParam:"style=simple,explode=false,name=snapshot"`
	// A Snapshot object
	Snapshot1 components.SnapshotInput `request:"mediaType=application/json"`
}

func (o *SnapshotModifyRequest) GetVolume() string {
	if o == nil {
		return ""
	}
	return o.Volume
}

func (o *SnapshotModifyRequest) GetSnapshotPathParameter() string {
	if o == nil {
		return ""
	}
	return o.SnapshotPathParameter
}

func (o *SnapshotModifyRequest) GetSnapshot1() components.SnapshotInput {
	if o == nil {
		return components.SnapshotInput{}
	}
	return o.Snapshot1
}

type SnapshotModifyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A snapshot was updated successfully
	RegularResponse *components.RegularResponse
	Headers         map[string][]string
}

func (o *SnapshotModifyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SnapshotModifyResponse) GetRegularResponse() *components.RegularResponse {
	if o == nil {
		return nil
	}
	return o.RegularResponse
}

func (o *SnapshotModifyResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
