// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/internal/utils"
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type SnapshotDeleteRequest struct {
	Volume   string `pathParam:"style=simple,explode=false,name=volume"`
	Snapshot string `pathParam:"style=simple,explode=false,name=snapshot"`
	Force    *bool  `default:"false" queryParam:"style=form,explode=true,name=force"`
}

func (s SnapshotDeleteRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SnapshotDeleteRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SnapshotDeleteRequest) GetVolume() string {
	if o == nil {
		return ""
	}
	return o.Volume
}

func (o *SnapshotDeleteRequest) GetSnapshot() string {
	if o == nil {
		return ""
	}
	return o.Snapshot
}

func (o *SnapshotDeleteRequest) GetForce() *bool {
	if o == nil {
		return nil
	}
	return o.Force
}

type SnapshotDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A snapshot was deleted successfully
	RegularResponse *components.RegularResponse
	Headers         map[string][]string
}

func (o *SnapshotDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SnapshotDeleteResponse) GetRegularResponse() *components.RegularResponse {
	if o == nil {
		return nil
	}
	return o.RegularResponse
}

func (o *SnapshotDeleteResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
