// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type SnapshotsListRequest struct {
	Volume string `pathParam:"style=simple,explode=false,name=volume"`
}

func (o *SnapshotsListRequest) GetVolume() string {
	if o == nil {
		return ""
	}
	return o.Volume
}

type SnapshotsListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of snapshots
	Snapshots []components.Snapshot
	Headers   map[string][]string
}

func (o *SnapshotsListResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SnapshotsListResponse) GetSnapshots() []components.Snapshot {
	if o == nil {
		return nil
	}
	return o.Snapshots
}

func (o *SnapshotsListResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
