// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type SnapshotsListAllRequest struct {
	Capacity *bool `queryParam:"style=form,explode=true,name=capacity"`
}

func (o *SnapshotsListAllRequest) GetCapacity() *bool {
	if o == nil {
		return nil
	}
	return o.Capacity
}

type SnapshotsListAllResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of all snapshots
	Snapshots []components.Snapshot
	Headers   map[string][]string
}

func (o *SnapshotsListAllResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *SnapshotsListAllResponse) GetSnapshots() []components.Snapshot {
	if o == nil {
		return nil
	}
	return o.Snapshots
}

func (o *SnapshotsListAllResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
