// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type TenantTokenResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Tenant's Token retrieval was successful
	TenantTokenResponse *components.TenantTokenResponse
	Headers             map[string][]string
}

func (o *TenantTokenResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *TenantTokenResponse) GetTenantTokenResponse() *components.TenantTokenResponse {
	if o == nil {
		return nil
	}
	return o.TenantTokenResponse
}

func (o *TenantTokenResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
