// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type TenantRefreshTokenResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Refresh Token
	RefreshToken *components.RefreshToken
	Headers      map[string][]string
}

func (o *TenantRefreshTokenResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *TenantRefreshTokenResponse) GetRefreshToken() *components.RefreshToken {
	if o == nil {
		return nil
	}
	return o.RefreshToken
}

func (o *TenantRefreshTokenResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
