// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type TenanthostgetRequest struct {
	Tenanthosttoken string `header:"style=simple,explode=false,name=tenanthosttoken"`
}

func (o *TenanthostgetRequest) GetTenanthosttoken() string {
	if o == nil {
		return ""
	}
	return o.Tenanthosttoken
}

type TenanthostgetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Got Tenant's Host successfully
	GetTenantHostResponse *components.GetTenantHostResponse
	Headers               map[string][]string
}

func (o *TenanthostgetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *TenanthostgetResponse) GetGetTenantHostResponse() *components.GetTenantHostResponse {
	if o == nil {
		return nil
	}
	return o.GetTenantHostResponse
}

func (o *TenanthostgetResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
