// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type TenantusergetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Got Tenant's User successfully
	GetTenanUserResponse *components.GetTenanUserResponse
	Headers              map[string][]string
}

func (o *TenantusergetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *TenantusergetResponse) GetGetTenanUserResponse() *components.GetTenanUserResponse {
	if o == nil {
		return nil
	}
	return o.GetTenanUserResponse
}

func (o *TenantusergetResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
