// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type TenantIDgetRequest struct {
	Tenanttoken string `header:"style=simple,explode=false,name=tenanttoken"`
}

func (o *TenantIDgetRequest) GetTenanttoken() string {
	if o == nil {
		return ""
	}
	return o.Tenanttoken
}

type TenantIDgetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Got Tenant's ID successfully
	GetTenantIDResponse *components.GetTenantIDResponse
	Headers             map[string][]string
}

func (o *TenantIDgetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *TenantIDgetResponse) GetGetTenantIDResponse() *components.GetTenantIDResponse {
	if o == nil {
		return nil
	}
	return o.GetTenantIDResponse
}

func (o *TenantIDgetResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
