// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type TenanthostdeleteRequest struct {
	TenantID   string `pathParam:"style=simple,explode=false,name=tenantID"`
	TenantHost string `pathParam:"style=simple,explode=false,name=tenantHost"`
}

func (o *TenanthostdeleteRequest) GetTenantID() string {
	if o == nil {
		return ""
	}
	return o.TenantID
}

func (o *TenanthostdeleteRequest) GetTenantHost() string {
	if o == nil {
		return ""
	}
	return o.TenantHost
}

type TenanthostdeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Tenant Host was deleted successfully
	TenantHostDeleteResponse *components.TenantHostDeleteResponse
	Headers                  map[string][]string
}

func (o *TenanthostdeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *TenanthostdeleteResponse) GetTenantHostDeleteResponse() *components.TenantHostDeleteResponse {
	if o == nil {
		return nil
	}
	return o.TenantHostDeleteResponse
}

func (o *TenanthostdeleteResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
