// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type UserConfirmRequest struct {
	// Cognito Client ID
	ClientID string `queryParam:"style=form,explode=true,name=client_id"`
	// Cognito User Name
	UserName string `queryParam:"style=form,explode=true,name=user_name"`
	// Cognito Signup Confirmation Code
	ConfirmationCode string `queryParam:"style=form,explode=true,name=confirmation_code"`
}

func (o *UserConfirmRequest) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

func (o *UserConfirmRequest) GetUserName() string {
	if o == nil {
		return ""
	}
	return o.UserName
}

func (o *UserConfirmRequest) GetConfirmationCode() string {
	if o == nil {
		return ""
	}
	return o.ConfirmationCode
}

type UserConfirmResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// User has successfully confirmed
	RegularResponse *components.RegularResponse
	Headers         map[string][]string
}

func (o *UserConfirmResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UserConfirmResponse) GetRegularResponse() *components.RegularResponse {
	if o == nil {
		return nil
	}
	return o.RegularResponse
}

func (o *UserConfirmResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
