// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type UserCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successfully Signed up
	SignUpResponse *components.SignUpResponse
	Headers        map[string][]string
}

func (o *UserCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UserCreateResponse) GetSignUpResponse() *components.SignUpResponse {
	if o == nil {
		return nil
	}
	return o.SignUpResponse
}

func (o *UserCreateResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
