// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type VersionGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Version of sio
	VersionResponse *components.VersionResponse
	Headers         map[string][]string
}

func (o *VersionGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *VersionGetResponse) GetVersionResponse() *components.VersionResponse {
	if o == nil {
		return nil
	}
	return o.VersionResponse
}

func (o *VersionGetResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
