// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type VirtualMediaListRequest struct {
	Startfrom *string `queryParam:"style=form,explode=true,name=startfrom"`
	Count     *int64  `queryParam:"style=form,explode=true,name=count"`
}

func (o *VirtualMediaListRequest) GetStartfrom() *string {
	if o == nil {
		return nil
	}
	return o.Startfrom
}

func (o *VirtualMediaListRequest) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

type VirtualMediaListResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of media
	VirtualMedias []components.VirtualMedia
	Headers       map[string][]string
}

func (o *VirtualMediaListResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *VirtualMediaListResponse) GetVirtualMedias() []components.VirtualMedia {
	if o == nil {
		return nil
	}
	return o.VirtualMedias
}

func (o *VirtualMediaListResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
