// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type VirtualMediaCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Virtual media has been created successfully
	SuccessJobResponse *components.SuccessJobResponse
	Headers            map[string][]string
}

func (o *VirtualMediaCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *VirtualMediaCreateResponse) GetSuccessJobResponse() *components.SuccessJobResponse {
	if o == nil {
		return nil
	}
	return o.SuccessJobResponse
}

func (o *VirtualMediaCreateResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
