// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type VolumeModifyRequest struct {
	VolumePathParameter string `pathParam:"style=simple,explode=false,name=volume"`
	// A Volume object
	Volume1 components.VolumeInput `request:"mediaType=application/json"`
}

func (o *VolumeModifyRequest) GetVolumePathParameter() string {
	if o == nil {
		return ""
	}
	return o.VolumePathParameter
}

func (o *VolumeModifyRequest) GetVolume1() components.VolumeInput {
	if o == nil {
		return components.VolumeInput{}
	}
	return o.Volume1
}

type VolumeModifyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A volume was updated successfully
	RegularResponse *components.RegularResponse
	Headers         map[string][]string
}

func (o *VolumeModifyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *VolumeModifyResponse) GetRegularResponse() *components.RegularResponse {
	if o == nil {
		return nil
	}
	return o.RegularResponse
}

func (o *VolumeModifyResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
