// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/internal/utils"
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type VolumeDeleteRequest struct {
	Volume string `pathParam:"style=simple,explode=false,name=volume"`
	Force  *bool  `default:"false" queryParam:"style=form,explode=true,name=force"`
}

func (v VolumeDeleteRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VolumeDeleteRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *VolumeDeleteRequest) GetVolume() string {
	if o == nil {
		return ""
	}
	return o.Volume
}

func (o *VolumeDeleteRequest) GetForce() *bool {
	if o == nil {
		return nil
	}
	return o.Force
}

type VolumeDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// A volume was deleted successfully
	RegularResponse *components.RegularResponse
	Headers         map[string][]string
}

func (o *VolumeDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *VolumeDeleteResponse) GetRegularResponse() *components.RegularResponse {
	if o == nil {
		return nil
	}
	return o.RegularResponse
}

func (o *VolumeDeleteResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
