// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type VolumeRecoverInitiateRequest struct {
	Volume string `pathParam:"style=simple,explode=false,name=volume"`
}

func (o *VolumeRecoverInitiateRequest) GetVolume() string {
	if o == nil {
		return ""
	}
	return o.Volume
}

type VolumeRecoverInitiateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Volume recovery was initiated successfully
	RegularResponse *components.RegularResponse
	Headers         map[string][]string
}

func (o *VolumeRecoverInitiateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *VolumeRecoverInitiateResponse) GetRegularResponse() *components.RegularResponse {
	if o == nil {
		return nil
	}
	return o.RegularResponse
}

func (o *VolumeRecoverInitiateResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
