// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/avivlevitski-vlz/volumez-sdk/models/components"
)

type VolumeGetRequest struct {
	Volume string `pathParam:"style=simple,explode=false,name=volume"`
}

func (o *VolumeGetRequest) GetVolume() string {
	if o == nil {
		return ""
	}
	return o.Volume
}

type VolumeGetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Properties of a volume
	Volume  *components.Volume
	Headers map[string][]string
}

func (o *VolumeGetResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *VolumeGetResponse) GetVolume() *components.Volume {
	if o == nil {
		return nil
	}
	return o.Volume
}

func (o *VolumeGetResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
