// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AssociationModify struct {
	Name     *string `json:"name,omitempty"`
	Snapshot *string `json:"snapshot,omitempty"`
	Selector *string `json:"selector,omitempty"`
}

func (o *AssociationModify) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *AssociationModify) GetSnapshot() *string {
	if o == nil {
		return nil
	}
	return o.Snapshot
}

func (o *AssociationModify) GetSelector() *string {
	if o == nil {
		return nil
	}
	return o.Selector
}
