// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AssociationCreate struct {
	Name       *string `json:"name,omitempty"`
	Volume     *string `json:"volume,omitempty"`
	Snapshot   *string `json:"snapshot,omitempty"`
	Mountpoint *string `json:"mountpoint,omitempty"`
	Selector   *string `json:"selector,omitempty"`
}

func (o *AssociationCreate) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *AssociationCreate) GetVolume() *string {
	if o == nil {
		return nil
	}
	return o.Volume
}

func (o *AssociationCreate) GetSnapshot() *string {
	if o == nil {
		return nil
	}
	return o.Snapshot
}

func (o *AssociationCreate) GetMountpoint() *string {
	if o == nil {
		return nil
	}
	return o.Mountpoint
}

func (o *AssociationCreate) GetSelector() *string {
	if o == nil {
		return nil
	}
	return o.Selector
}
