// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Association struct {
	Name         *string `json:"name,omitempty"`
	ID           *string `json:"id,omitempty"`
	Volumename   *string `json:"volumename,omitempty"`
	Volumeid     *string `json:"volumeid,omitempty"`
	Snapshotname *string `json:"snapshotname,omitempty"`
	Snapshotid   *string `json:"snapshotid,omitempty"`
	State        *string `json:"state,omitempty"`
	Status       *string `json:"status,omitempty"`
}

func (o *Association) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Association) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Association) GetVolumename() *string {
	if o == nil {
		return nil
	}
	return o.Volumename
}

func (o *Association) GetVolumeid() *string {
	if o == nil {
		return nil
	}
	return o.Volumeid
}

func (o *Association) GetSnapshotname() *string {
	if o == nil {
		return nil
	}
	return o.Snapshotname
}

func (o *Association) GetSnapshotid() *string {
	if o == nil {
		return nil
	}
	return o.Snapshotid
}

func (o *Association) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *Association) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}
