// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Attachment struct {
	Volumename         *string `json:"volumename,omitempty"`
	Volumeid           *string `json:"volumeid,omitempty"`
	Snapshotname       *string `json:"snapshotname,omitempty"`
	Snapshotid         *string `json:"snapshotid,omitempty"`
	Node               string  `json:"node"`
	State              *string `json:"state,omitempty"`
	Status             *string `json:"status,omitempty"`
	Progress           *int64  `json:"progress,omitempty"`
	Mountpoint         *string `json:"mountpoint,omitempty"`
	Readonly           *bool   `json:"readonly,omitempty"`
	AllocatedResources *int64  `json:"allocated_resources,omitempty"`
}

func (o *Attachment) GetVolumename() *string {
	if o == nil {
		return nil
	}
	return o.Volumename
}

func (o *Attachment) GetVolumeid() *string {
	if o == nil {
		return nil
	}
	return o.Volumeid
}

func (o *Attachment) GetSnapshotname() *string {
	if o == nil {
		return nil
	}
	return o.Snapshotname
}

func (o *Attachment) GetSnapshotid() *string {
	if o == nil {
		return nil
	}
	return o.Snapshotid
}

func (o *Attachment) GetNode() string {
	if o == nil {
		return ""
	}
	return o.Node
}

func (o *Attachment) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *Attachment) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *Attachment) GetProgress() *int64 {
	if o == nil {
		return nil
	}
	return o.Progress
}

func (o *Attachment) GetMountpoint() *string {
	if o == nil {
		return nil
	}
	return o.Mountpoint
}

func (o *Attachment) GetReadonly() *bool {
	if o == nil {
		return nil
	}
	return o.Readonly
}

func (o *Attachment) GetAllocatedResources() *int64 {
	if o == nil {
		return nil
	}
	return o.AllocatedResources
}
