// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AttachmentInput struct {
	Volumename         *string `json:"volumename,omitempty"`
	Snapshotname       *string `json:"snapshotname,omitempty"`
	Node               string  `json:"node"`
	Mountpoint         *string `json:"mountpoint,omitempty"`
	Readonly           *bool   `json:"readonly,omitempty"`
	AllocatedResources *int64  `json:"allocated_resources,omitempty"`
}

func (o *AttachmentInput) GetVolumename() *string {
	if o == nil {
		return nil
	}
	return o.Volumename
}

func (o *AttachmentInput) GetSnapshotname() *string {
	if o == nil {
		return nil
	}
	return o.Snapshotname
}

func (o *AttachmentInput) GetNode() string {
	if o == nil {
		return ""
	}
	return o.Node
}

func (o *AttachmentInput) GetMountpoint() *string {
	if o == nil {
		return nil
	}
	return o.Mountpoint
}

func (o *AttachmentInput) GetReadonly() *bool {
	if o == nil {
		return nil
	}
	return o.Readonly
}

func (o *AttachmentInput) GetAllocatedResources() *int64 {
	if o == nil {
		return nil
	}
	return o.AllocatedResources
}
