// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Chap struct {
	User     *string `json:"user,omitempty"`
	Password *string `json:"password,omitempty"`
}

func (o *Chap) GetUser() *string {
	if o == nil {
		return nil
	}
	return o.User
}

func (o *Chap) GetPassword() *string {
	if o == nil {
		return nil
	}
	return o.Password
}

type Authentication struct {
	Method *string `json:"method,omitempty"`
	Chap   *Chap   `json:"chap,omitempty"`
}

func (o *Authentication) GetMethod() *string {
	if o == nil {
		return nil
	}
	return o.Method
}

func (o *Authentication) GetChap() *Chap {
	if o == nil {
		return nil
	}
	return o.Chap
}
