// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CapacityGroup struct {
	Name *string `json:"name,omitempty"`
}

func (o *CapacityGroup) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
