// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ChangePasswordRequest struct {
	Password *string `json:"password,omitempty"`
	Name     *string `json:"name,omitempty"`
	GUID     *string `json:"guid,omitempty"`
}

func (o *ChangePasswordRequest) GetPassword() *string {
	if o == nil {
		return nil
	}
	return o.Password
}

func (o *ChangePasswordRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ChangePasswordRequest) GetGUID() *string {
	if o == nil {
		return nil
	}
	return o.GUID
}
