// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ChangePasswordRequestLoggedIn struct {
	Oldpassword *string `json:"oldpassword,omitempty"`
	Email       *string `json:"email,omitempty"`
	Newpassword *string `json:"newpassword,omitempty"`
}

func (o *ChangePasswordRequestLoggedIn) GetOldpassword() *string {
	if o == nil {
		return nil
	}
	return o.Oldpassword
}

func (o *ChangePasswordRequestLoggedIn) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *ChangePasswordRequestLoggedIn) GetNewpassword() *string {
	if o == nil {
		return nil
	}
	return o.Newpassword
}
