// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Connectivity struct {
	Name                 string `json:"name"`
	Zones1               string `json:"zones1"`
	Systemtypes1         string `json:"systemtypes1"`
	Zones2               string `json:"zones2"`
	Systemtypes2         string `json:"systemtypes2"`
	Mediaprotocol        string `json:"mediaprotocol"`
	Replicationprotocol  string `json:"replicationprotocol"`
	Replicationbandwidth *int64 `json:"replicationbandwidth,omitempty"`
}

func (o *Connectivity) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Connectivity) GetZones1() string {
	if o == nil {
		return ""
	}
	return o.Zones1
}

func (o *Connectivity) GetSystemtypes1() string {
	if o == nil {
		return ""
	}
	return o.Systemtypes1
}

func (o *Connectivity) GetZones2() string {
	if o == nil {
		return ""
	}
	return o.Zones2
}

func (o *Connectivity) GetSystemtypes2() string {
	if o == nil {
		return ""
	}
	return o.Systemtypes2
}

func (o *Connectivity) GetMediaprotocol() string {
	if o == nil {
		return ""
	}
	return o.Mediaprotocol
}

func (o *Connectivity) GetReplicationprotocol() string {
	if o == nil {
		return ""
	}
	return o.Replicationprotocol
}

func (o *Connectivity) GetReplicationbandwidth() *int64 {
	if o == nil {
		return nil
	}
	return o.Replicationbandwidth
}
