// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ErrorResponse struct {
	Message *string `json:"message,omitempty"`
}

func (o *ErrorResponse) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}
