// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Nodes struct {
	Node *string `json:"node,omitempty"`
	Role *string `json:"role,omitempty"`
}

func (o *Nodes) GetNode() *string {
	if o == nil {
		return nil
	}
	return o.Node
}

func (o *Nodes) GetRole() *string {
	if o == nil {
		return nil
	}
	return o.Role
}

type ExportCreate struct {
	TargetName     *string         `json:"target_name,omitempty"`
	Protocol       *string         `json:"protocol,omitempty"`
	Authentication *Authentication `json:"authentication,omitempty"`
	Volumeid       *string         `json:"volumeid,omitempty"`
	Snapshotid     *string         `json:"snapshotid,omitempty"`
	AllowedHosts   []string        `json:"allowed_hosts,omitempty"`
	Nodes          []Nodes         `json:"nodes,omitempty"`
}

func (o *ExportCreate) GetTargetName() *string {
	if o == nil {
		return nil
	}
	return o.TargetName
}

func (o *ExportCreate) GetProtocol() *string {
	if o == nil {
		return nil
	}
	return o.Protocol
}

func (o *ExportCreate) GetAuthentication() *Authentication {
	if o == nil {
		return nil
	}
	return o.Authentication
}

func (o *ExportCreate) GetVolumeid() *string {
	if o == nil {
		return nil
	}
	return o.Volumeid
}

func (o *ExportCreate) GetSnapshotid() *string {
	if o == nil {
		return nil
	}
	return o.Snapshotid
}

func (o *ExportCreate) GetAllowedHosts() []string {
	if o == nil {
		return nil
	}
	return o.AllowedHosts
}

func (o *ExportCreate) GetNodes() []Nodes {
	if o == nil {
		return nil
	}
	return o.Nodes
}
