// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetTenantRefreshTokenRequest struct {
	Accesstoken string `json:"accesstoken"`
	Hostname    string `json:"hostname"`
}

func (o *GetTenantRefreshTokenRequest) GetAccesstoken() string {
	if o == nil {
		return ""
	}
	return o.Accesstoken
}

func (o *GetTenantRefreshTokenRequest) GetHostname() string {
	if o == nil {
		return ""
	}
	return o.Hostname
}
