// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetTenantHostResponse struct {
	StatusCode int64   `json:"StatusCode"`
	Message    *string `json:"Message,omitempty"`
	TenantHost *string `json:"TenantHost,omitempty"`
	TenantID   *string `json:"TenantID,omitempty"`
}

func (o *GetTenantHostResponse) GetStatusCode() int64 {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetTenantHostResponse) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *GetTenantHostResponse) GetTenantHost() *string {
	if o == nil {
		return nil
	}
	return o.TenantHost
}

func (o *GetTenantHostResponse) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}
