// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetTenanUserResponse struct {
	StatusCode *int64  `json:"StatusCode,omitempty"`
	Message    *string `json:"Message,omitempty"`
	Email      *string `json:"Email,omitempty"`
	Name       *string `json:"Name,omitempty"`
	TenantID   *string `json:"TenantID,omitempty"`
}

func (o *GetTenanUserResponse) GetStatusCode() *int64 {
	if o == nil {
		return nil
	}
	return o.StatusCode
}

func (o *GetTenanUserResponse) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *GetTenanUserResponse) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *GetTenanUserResponse) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *GetTenanUserResponse) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}
