// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GetTenantIDResponse struct {
	StatusCode int64   `json:"StatusCode"`
	Message    *string `json:"Message,omitempty"`
	TenantID   *string `json:"TenantID,omitempty"`
}

func (o *GetTenantIDResponse) GetStatusCode() int64 {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetTenantIDResponse) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *GetTenantIDResponse) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}
