// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MachineInfo struct {
	Instanceid     *string `json:"instanceid,omitempty"`
	Instancetype   *string `json:"instancetype,omitempty"`
	Controladdress *string `json:"controladdress,omitempty"`
	Imageid        *string `json:"imageid,omitempty"`
	Zone           *string `json:"zone,omitempty"`
	Sha            *string `json:"sha,omitempty"`
}

func (o *MachineInfo) GetInstanceid() *string {
	if o == nil {
		return nil
	}
	return o.Instanceid
}

func (o *MachineInfo) GetInstancetype() *string {
	if o == nil {
		return nil
	}
	return o.Instancetype
}

func (o *MachineInfo) GetControladdress() *string {
	if o == nil {
		return nil
	}
	return o.Controladdress
}

func (o *MachineInfo) GetImageid() *string {
	if o == nil {
		return nil
	}
	return o.Imageid
}

func (o *MachineInfo) GetZone() *string {
	if o == nil {
		return nil
	}
	return o.Zone
}

func (o *MachineInfo) GetSha() *string {
	if o == nil {
		return nil
	}
	return o.Sha
}
