// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MediaAssign struct {
	CapacityGroup *string `json:"capacity_group,omitempty"`
	// Profile media even if it was already profiled
	Reprofile *bool `json:"reprofile,omitempty"`
	// LBA size for media format
	Blocksize *int64 `json:"blocksize,omitempty"`
}

func (o *MediaAssign) GetCapacityGroup() *string {
	if o == nil {
		return nil
	}
	return o.CapacityGroup
}

func (o *MediaAssign) GetReprofile() *bool {
	if o == nil {
		return nil
	}
	return o.Reprofile
}

func (o *MediaAssign) GetBlocksize() *int64 {
	if o == nil {
		return nil
	}
	return o.Blocksize
}
