// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MediaModify struct {
	Offlinetime *string `json:"offlinetime,omitempty"`
}

func (o *MediaModify) GetOfflinetime() *string {
	if o == nil {
		return nil
	}
	return o.Offlinetime
}
