// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MediaProfile struct {
	Iopsread           *int64 `json:"iopsread,omitempty"`
	Iopswrite          *int64 `json:"iopswrite,omitempty"`
	Bandwidthread      *int64 `json:"bandwidthread,omitempty"`
	Bandwidthwrite     *int64 `json:"bandwidthwrite,omitempty"`
	Latencyread        *int64 `json:"latencyread,omitempty"`
	Latencywrite       *int64 `json:"latencywrite,omitempty"`
	Freeiopsread       *int64 `json:"freeiopsread,omitempty"`
	Freeiopswrite      *int64 `json:"freeiopswrite,omitempty"`
	Freebandwidthread  *int64 `json:"freebandwidthread,omitempty"`
	Freebandwidthwrite *int64 `json:"freebandwidthwrite,omitempty"`
}

func (o *MediaProfile) GetIopsread() *int64 {
	if o == nil {
		return nil
	}
	return o.Iopsread
}

func (o *MediaProfile) GetIopswrite() *int64 {
	if o == nil {
		return nil
	}
	return o.Iopswrite
}

func (o *MediaProfile) GetBandwidthread() *int64 {
	if o == nil {
		return nil
	}
	return o.Bandwidthread
}

func (o *MediaProfile) GetBandwidthwrite() *int64 {
	if o == nil {
		return nil
	}
	return o.Bandwidthwrite
}

func (o *MediaProfile) GetLatencyread() *int64 {
	if o == nil {
		return nil
	}
	return o.Latencyread
}

func (o *MediaProfile) GetLatencywrite() *int64 {
	if o == nil {
		return nil
	}
	return o.Latencywrite
}

func (o *MediaProfile) GetFreeiopsread() *int64 {
	if o == nil {
		return nil
	}
	return o.Freeiopsread
}

func (o *MediaProfile) GetFreeiopswrite() *int64 {
	if o == nil {
		return nil
	}
	return o.Freeiopswrite
}

func (o *MediaProfile) GetFreebandwidthread() *int64 {
	if o == nil {
		return nil
	}
	return o.Freebandwidthread
}

func (o *MediaProfile) GetFreebandwidthwrite() *int64 {
	if o == nil {
		return nil
	}
	return o.Freebandwidthwrite
}
