// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Tags struct {
}

type Node struct {
	Instanceid     *string `json:"instanceid,omitempty"`
	Name           string  `json:"name"`
	Os             string  `json:"os"`
	Osversion      *string `json:"osversion,omitempty"`
	Kversion       *string `json:"kversion,omitempty"`
	Controladdress *string `json:"controladdress,omitempty"`
	Credential     *string `json:"credential,omitempty"`
	AccountID      *string `json:"accountID,omitempty"`
	Region         *string `json:"region,omitempty"`
	Zone           *string `json:"zone,omitempty"`
	// global namespace for resources in account empty if not aviliable/supported on cloud provider/node
	ResourceNamespace *string `json:"ResourceNamespace,omitempty"`
	// identifier of the physical location of the node empty if not aviliable/supported on on cloud provider/node
	PhysicalProximityGroup *string `json:"PhysicalProximityGroup,omitempty"`
	// virtual domain for the node fault domains if aviliable/supported on on cloud provider/node
	ResiliencyDomain *string `json:"ResiliencyDomain,omitempty"`
	// identifier for node in FaultDomain
	FaultDomain            *string `json:"FaultDomain,omitempty"`
	Offlinetime            *string `json:"offlinetime,omitempty"`
	State                  *string `json:"state,omitempty"`
	Status                 *string `json:"status,omitempty"`
	Progress               *int64  `json:"progress,omitempty"`
	Connectorversion       *string `json:"connectorversion,omitempty"`
	Label                  *string `json:"label,omitempty"`
	Tags                   *Tags   `json:"tags,omitempty"`
	Cloudprovider          *string `json:"cloudprovider,omitempty"`
	Nodecluster            *string `json:"nodecluster,omitempty"`
	AutoprovisionInfraUUID *string `json:"autoprovisionInfraUUID,omitempty"`
	Instancetype           *string `json:"instancetype,omitempty"`
}

func (o *Node) GetInstanceid() *string {
	if o == nil {
		return nil
	}
	return o.Instanceid
}

func (o *Node) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Node) GetOs() string {
	if o == nil {
		return ""
	}
	return o.Os
}

func (o *Node) GetOsversion() *string {
	if o == nil {
		return nil
	}
	return o.Osversion
}

func (o *Node) GetKversion() *string {
	if o == nil {
		return nil
	}
	return o.Kversion
}

func (o *Node) GetControladdress() *string {
	if o == nil {
		return nil
	}
	return o.Controladdress
}

func (o *Node) GetCredential() *string {
	if o == nil {
		return nil
	}
	return o.Credential
}

func (o *Node) GetAccountID() *string {
	if o == nil {
		return nil
	}
	return o.AccountID
}

func (o *Node) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *Node) GetZone() *string {
	if o == nil {
		return nil
	}
	return o.Zone
}

func (o *Node) GetResourceNamespace() *string {
	if o == nil {
		return nil
	}
	return o.ResourceNamespace
}

func (o *Node) GetPhysicalProximityGroup() *string {
	if o == nil {
		return nil
	}
	return o.PhysicalProximityGroup
}

func (o *Node) GetResiliencyDomain() *string {
	if o == nil {
		return nil
	}
	return o.ResiliencyDomain
}

func (o *Node) GetFaultDomain() *string {
	if o == nil {
		return nil
	}
	return o.FaultDomain
}

func (o *Node) GetOfflinetime() *string {
	if o == nil {
		return nil
	}
	return o.Offlinetime
}

func (o *Node) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *Node) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *Node) GetProgress() *int64 {
	if o == nil {
		return nil
	}
	return o.Progress
}

func (o *Node) GetConnectorversion() *string {
	if o == nil {
		return nil
	}
	return o.Connectorversion
}

func (o *Node) GetLabel() *string {
	if o == nil {
		return nil
	}
	return o.Label
}

func (o *Node) GetTags() *Tags {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *Node) GetCloudprovider() *string {
	if o == nil {
		return nil
	}
	return o.Cloudprovider
}

func (o *Node) GetNodecluster() *string {
	if o == nil {
		return nil
	}
	return o.Nodecluster
}

func (o *Node) GetAutoprovisionInfraUUID() *string {
	if o == nil {
		return nil
	}
	return o.AutoprovisionInfraUUID
}

func (o *Node) GetInstancetype() *string {
	if o == nil {
		return nil
	}
	return o.Instancetype
}
