// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NodeDescribeResponse struct {
	// Map of volume IDs to volume objects
	VolumesMap map[string]Volume `json:"volumesMap,omitempty"`
}

func (o *NodeDescribeResponse) GetVolumesMap() map[string]Volume {
	if o == nil {
		return nil
	}
	return o.VolumesMap
}
