// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Plan struct {
	Volumegroup            VolumeGroup  `json:"volumegroup"`
	Replicationvolumegroup *VolumeGroup `json:"replicationvolumegroup,omitempty"`
}

func (o *Plan) GetVolumegroup() VolumeGroup {
	if o == nil {
		return VolumeGroup{}
	}
	return o.Volumegroup
}

func (o *Plan) GetReplicationvolumegroup() *VolumeGroup {
	if o == nil {
		return nil
	}
	return o.Replicationvolumegroup
}
