// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RefreshTokenResponse struct {
	AccessToken           *string `json:"AccessToken,omitempty"`
	IDToken               *string `json:"IdToken,omitempty"`
	AccessTokenExpiration *string `json:"AccessTokenExpiration,omitempty"`
	IDTokenExpiration     *string `json:"IdTokenExpiration,omitempty"`
	TokenType             *string `json:"TokenType,omitempty"`
}

func (o *RefreshTokenResponse) GetAccessToken() *string {
	if o == nil {
		return nil
	}
	return o.AccessToken
}

func (o *RefreshTokenResponse) GetIDToken() *string {
	if o == nil {
		return nil
	}
	return o.IDToken
}

func (o *RefreshTokenResponse) GetAccessTokenExpiration() *string {
	if o == nil {
		return nil
	}
	return o.AccessTokenExpiration
}

func (o *RefreshTokenResponse) GetIDTokenExpiration() *string {
	if o == nil {
		return nil
	}
	return o.IDTokenExpiration
}

func (o *RefreshTokenResponse) GetTokenType() *string {
	if o == nil {
		return nil
	}
	return o.TokenType
}
