// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RegularResponse struct {
	Message *string `json:"Message,omitempty"`
}

func (o *RegularResponse) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}
