// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	StorageIoAuthorizer *string `security:"scheme,type=apiKey,subtype=header,name=authorization,env=volumezsdk_storage_io_authorizer"`
}

func (o *Security) GetStorageIoAuthorizer() *string {
	if o == nil {
		return nil
	}
	return o.StorageIoAuthorizer
}
