// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SignoutRequest struct {
	AccessToken string `json:"AccessToken"`
}

func (o *SignoutRequest) GetAccessToken() string {
	if o == nil {
		return ""
	}
	return o.AccessToken
}
