// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SignInResponse struct {
	AccessToken  string `json:"AccessToken"`
	IDToken      string `json:"IdToken"`
	RefreshToken string `json:"RefreshToken"`
	ExpiresIn    int64  `json:"ExpiresIn"`
	TokenType    string `json:"TokenType"`
}

func (o *SignInResponse) GetAccessToken() string {
	if o == nil {
		return ""
	}
	return o.AccessToken
}

func (o *SignInResponse) GetIDToken() string {
	if o == nil {
		return ""
	}
	return o.IDToken
}

func (o *SignInResponse) GetRefreshToken() string {
	if o == nil {
		return ""
	}
	return o.RefreshToken
}

func (o *SignInResponse) GetExpiresIn() int64 {
	if o == nil {
		return 0
	}
	return o.ExpiresIn
}

func (o *SignInResponse) GetTokenType() string {
	if o == nil {
		return ""
	}
	return o.TokenType
}
