// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SignIn struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (o *SignIn) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *SignIn) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}
