// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SignUpResponse struct {
	Status  int64  `json:"status"`
	Message string `json:"message"`
}

func (o *SignUpResponse) GetStatus() int64 {
	if o == nil {
		return 0
	}
	return o.Status
}

func (o *SignUpResponse) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}
