// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SuccessJobResponse struct {
	Message  *string `json:"Message,omitempty"`
	JobID    *string `json:"JobID,omitempty"`
	ObjectID *string `json:"ObjectID,omitempty"`
}

func (o *SuccessJobResponse) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *SuccessJobResponse) GetJobID() *string {
	if o == nil {
		return nil
	}
	return o.JobID
}

func (o *SuccessJobResponse) GetObjectID() *string {
	if o == nil {
		return nil
	}
	return o.ObjectID
}
