// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TenantCreateUserRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

func (o *TenantCreateUserRequest) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *TenantCreateUserRequest) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}

func (o *TenantCreateUserRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
