// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TenantHostDeleteResponse struct {
	StatusCode int64   `json:"StatusCode"`
	Message    *string `json:"Message,omitempty"`
}

func (o *TenantHostDeleteResponse) GetStatusCode() int64 {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *TenantHostDeleteResponse) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}
