// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TenantTokenResponse struct {
	AccessToken string `json:"AccessToken"`
	TokenType   string `json:"TokenType"`
	ExpiresIn   int64  `json:"ExpiresIn"`
}

func (o *TenantTokenResponse) GetAccessToken() string {
	if o == nil {
		return ""
	}
	return o.AccessToken
}

func (o *TenantTokenResponse) GetTokenType() string {
	if o == nil {
		return ""
	}
	return o.TokenType
}

func (o *TenantTokenResponse) GetExpiresIn() int64 {
	if o == nil {
		return 0
	}
	return o.ExpiresIn
}
