// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type VolumePlanOutput struct {
	Message *string `json:"Message,omitempty"`
	Success *bool   `json:"Success,omitempty"`
	Plans   []Plan  `json:"Plans,omitempty"`
}

func (o *VolumePlanOutput) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *VolumePlanOutput) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}

func (o *VolumePlanOutput) GetPlans() []Plan {
	if o == nil {
		return nil
	}
	return o.Plans
}
