// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
)

type GetTenanUserResponse struct {
	StatusCode *int64  `json:"StatusCode,omitempty"`
	Message    *string `json:"Message,omitempty"`
	Email      *string `json:"Email,omitempty"`
	Name       *string `json:"Name,omitempty"`
	TenantID   *string `json:"TenantID,omitempty"`
}

var _ error = &GetTenanUserResponse{}

func (e *GetTenanUserResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
