// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
)

type GetTenantIDResponse struct {
	StatusCode int64   `json:"StatusCode"`
	Message    *string `json:"Message,omitempty"`
	TenantID   *string `json:"TenantID,omitempty"`
}

var _ error = &GetTenantIDResponse{}

func (e *GetTenantIDResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
