// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
)

type TenantHostDeleteResponse struct {
	StatusCode int64   `json:"StatusCode"`
	Message    *string `json:"Message,omitempty"`
}

var _ error = &TenantHostDeleteResponse{}

func (e *TenantHostDeleteResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
