workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    saas-dev-avivl:
        inputs:
            - location: .openapi.json
        registry:
            location: registry.speakeasyapi.dev/volumez/saas/saas-dev-avivl
targets:
    volumez-sdk:
        target: go
        source: saas-dev-avivl
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/volumez/saas/saas-dev-avivl-go-code-samples
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
